version: '3.4'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: RootToor396a
    volumes:
      - mongo_data:/data/db
    ports:
    - 27017:27017
  csvsource:
    build:
      context: .
      dockerfile: Dockerfile-csv
    ports:
    - 3000:3000
  prodcatalog1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000
  prodcatalog2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - prodcatalog1
      - prodcatalog2
    volumes:
      - ./etc:/etc/nginx/conf.d
    ports:
      - 80:80
volumes:
  mongo_data: